package engine

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/threatcl/drift-action/internal/config"
	"github.com/threatcl/drift-action/internal/deps"
	"github.com/threatcl/drift-action/internal/diff"
	"github.com/threatcl/drift-action/internal/model"
)

const testModel = `spec_version = "0.7.0"

threatmodel "login service" {
  description = "Login service for the customer web app"
  author      = "@test"

  threat "credential stuffing" {
    description = "Automated credential stuffing against POST /login"
    impacts     = ["Confidentiality"]
    stride      = ["Spoofing"]

    control "login rate limiting" {
      description = "Per-IP token-bucket rate limiting on POST /login, implemented in internal/auth/ratelimit.go"
      implemented = true
    }
  }
}
`

// testWorkspace writes a threat model plus the file its prose references, and
// returns the loaded assertions. The reference is what makes context stuffing
// engage: SelectContext sends the intersection of referenced and touched.
func testWorkspace(t *testing.T) (string, *model.Assertions) {
	t.Helper()
	dir := t.TempDir()

	write := func(rel, contents string) {
		path := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("app.tm.hcl", testModel)
	write("internal/auth/ratelimit.go", "package auth\n\nfunc Allow(ip string) bool { return true }\n")

	assertions, err := model.LoadIn(dir, "app.tm.hcl")
	if err != nil {
		t.Fatalf("loading the test model: %v", err)
	}
	return dir, assertions
}

// TestAssembleRequestSetsEveryField guards the drift that put this package
// here. The corpus built its own llm.ReviewRequest and stopped setting
// Categories, so the ENABLED CATEGORIES prompt section was never exercised by
// a recording and nobody noticed. Reflecting over the struct means a field
// added to ReviewRequest and not wired in here fails a free test, rather than
// reaching production while the quality corpus keeps measuring a request
// without it.
func TestAssembleRequestSetsEveryField(t *testing.T) {
	dir, assertions := testWorkspace(t)

	cfg := config.Default()
	cfg.Categories = []string{"phantom_control"}

	changes := []diff.Change{
		{
			Path:   "internal/auth/ratelimit.go",
			Status: "modified",
			Patch:  "@@ -1,3 +1,3 @@\n package auth\n \n-func Allow(ip string) bool { return true }\n+func Allow(ip string) bool { return false }\n",
		},
		{
			Path:   "go.mod",
			Status: "modified",
			Patch:  "@@ -3,3 +3,3 @@\n require (\n-	github.com/example/thing v1.2.0\n+	github.com/example/thing v1.3.0\n )\n",
		},
	}

	assembly := AssembleRequest(cfg, RequestInput{
		Workspace:     dir,
		Assertions:    assertions,
		Kept:          changes,
		ManifestFacts: deps.Facts(changes),
	})

	request := reflect.ValueOf(assembly.Request)
	for i := range request.NumField() {
		if request.Field(i).IsZero() {
			t.Errorf("ReviewRequest.%s was left at its zero value — wire it into AssembleRequest, or the corpus measures a request the action does not send",
				request.Type().Field(i).Name)
		}
	}

	// The one the corpus actually lost. Worth asserting by name too: a future
	// reader deleting the reflection loop should still fail here.
	if len(assembly.Request.Categories) != 1 || assembly.Request.Categories[0] != "phantom_control" {
		t.Errorf("Categories did not reach the request: %v", assembly.Request.Categories)
	}
	if len(assembly.Request.ContextFiles) != 1 || assembly.Request.ContextFiles[0].Path != "internal/auth/ratelimit.go" {
		t.Errorf("context stuffing did not send the referenced-and-touched file: %v", assembly.Request.ContextFiles)
	}
}

// TestFilterChangesWiresEveryInput pins what FilterChanges hands the filter:
// the repo's ignore_paths and trigger_paths, the model's referenced paths, and
// a header check that really reads the checkout. Each is a way to lose or keep
// a file that a unit test of diff.Filter cannot see wired up.
func TestFilterChangesWiresEveryInput(t *testing.T) {
	dir, assertions := testWorkspace(t)
	write := func(rel, contents string) {
		path := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("internal/db/queries.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage db\n")
	write("internal/api/server.go", "package api\n")

	cfg := config.Default()
	cfg.IgnorePaths = []string{"examples/", "internal/auth/"}
	cfg.TriggerPaths = []string{"examples/keep/"}

	result := FilterChanges(cfg, dir, assertions, []diff.Change{
		{Path: "internal/api/server.go"},
		{Path: "internal/db/queries.go"},
		{Path: "examples/demo/main.go"},
		{Path: "examples/keep/main.go"},
		// Referenced by the model's prose, but ignored all the same: only
		// trigger_paths brings an ignored file back.
		{Path: "internal/auth/ratelimit.go"},
	})

	if got, want := diff.Paths(result.Kept), []string{"internal/api/server.go", "examples/keep/main.go"}; !reflect.DeepEqual(got, want) {
		t.Errorf("kept %v, want %v", got, want)
	}
	if want := []string{"internal/db/queries.go"}; !reflect.DeepEqual(result.Generated, want) {
		t.Errorf("Generated = %v, want %v — the header check did not read the checkout", result.Generated, want)
	}
	if want := []string{"examples/demo/main.go", "internal/auth/ratelimit.go"}; !reflect.DeepEqual(result.Ignored, want) {
		t.Errorf("Ignored = %v, want %v", result.Ignored, want)
	}
}

// A checkout that cannot be opened costs header detection and nothing else:
// the generated file is judged by name, and kept.
func TestFilterChangesWithoutCheckoutKeeps(t *testing.T) {
	_, assertions := testWorkspace(t)

	result := FilterChanges(config.Default(), filepath.Join(t.TempDir(), "absent"), assertions,
		[]diff.Change{{Path: "internal/db/queries.go"}})

	if len(result.Kept) != 1 {
		t.Errorf("kept %v, want the file kept when the checkout is unreadable", diff.Paths(result.Kept))
	}
}
