package diff

import (
	"path"
	"strings"
)

// DefaultNarrowAbove is the number of changed files below which nothing is
// narrowed away. Filtering exists to keep a huge diff within budget, not to
// pre-judge which files matter: the claude-plugin narrows only when a diff runs
// to hundreds of files, and a small PR is cheap to review whole. Below this
// threshold the only thing removed is noise.
const DefaultNarrowAbove = 50

// Options configures filtering. Patterns are in the language matchPattern
// describes.
type Options struct {
	// TriggerPatterns are the repo's trigger_paths: files to review whatever
	// else the rules say. They survive noise, IgnorePatterns and narrowing.
	TriggerPatterns []string
	// References are the paths the threat model's prose names. They survive
	// noise and narrowing — the model says these files matter — but not
	// IgnorePatterns. Prose cites paths loosely, so a bare "server.go" would
	// otherwise defeat an exclusion wherever a file of that name sits; a repo
	// that wants a referenced file reviewed despite an exclusion names it in
	// trigger_paths.
	References []string
	// IgnorePatterns are the repo's ignore_paths: files it has declared carry
	// no drift. They are removed before narrowing, so they never count
	// towards NarrowAbove.
	IgnorePatterns []string
	// Generated reports whether a file declares itself generated by its
	// contents rather than its name. Such files are noise. Nil means no file
	// is read and only names are judged.
	Generated func(path string) bool
	// NarrowAbove overrides DefaultNarrowAbove. Zero means use the default.
	NarrowAbove int
}

// Result is what survived filtering, and what did not.
type Result struct {
	Kept []Change
	// Noise counts files removed as documentation, lock files, vendored or
	// generated code — content that cannot carry threat model drift.
	Noise int
	// Generated lists the noise files recognised by a generated-code header
	// rather than by name. They are counted in Noise too, and named because
	// nothing in their path says why they were skipped.
	Generated []string
	// Ignored lists the files ignore_paths removed. Named rather than
	// counted: a configured exclusion is a choice about this repo, and the
	// reader has to be able to check what it actually took out.
	Ignored []string
	// Narrowed reports that the diff was large enough to require narrowing to
	// security-relevant paths, so coverage of this PR is partial and the
	// comment must say so.
	Narrowed bool
	// NarrowedOut counts source files narrowing removed.
	NarrowedOut int
}

// Filter reduces a diff to what is worth reviewing, in two stages. Noise and
// the repo's ignore_paths are always removed. Everything else is kept unless
// the diff is too large, in which case it is narrowed to security-relevant
// paths and Narrowed is set.
//
// The default is to keep. An earlier version inverted this — keeping only
// paths whose name contained a security keyword — which silently discarded
// ordinary source files like server.go and store.go, exactly the code a drift
// review has to read. ignore_paths is the one way to remove more, and it is
// the repo's explicit choice, reported file by file.
func Filter(changes []Change, opts Options) Result {
	threshold := opts.NarrowAbove
	if threshold <= 0 {
		threshold = DefaultNarrowAbove
	}

	candidates := make([]Change, 0, len(changes))
	result := Result{}
	for _, change := range changes {
		triggered := matchesAny(change.Path, opts.TriggerPatterns)
		named := triggered || matchesAny(change.Path, opts.References)

		// Order matters. Noise comes before ignore_paths so that Ignored
		// lists only files the exclusion actually changed the outcome for,
		// and the header check comes last because it is the one that reads
		// the file.
		switch {
		case !named && isNoise(change.Path):
			result.Noise++
		case !triggered && ignores(opts.IgnorePatterns, change.Path):
			result.Ignored = append(result.Ignored, change.Path)
		case !named && opts.Generated != nil && opts.Generated(change.Path):
			result.Noise++
			result.Generated = append(result.Generated, change.Path)
		default:
			candidates = append(candidates, change)
		}
	}

	if len(candidates) <= threshold {
		result.Kept = candidates
		return result
	}

	kept := make([]Change, 0, len(candidates))
	for _, change := range candidates {
		if matchesAny(change.Path, opts.TriggerPatterns) ||
			matchesAny(change.Path, opts.References) ||
			isSecurityRelevant(change.Path) {
			kept = append(kept, change)
		}
	}
	result.Kept = kept
	result.Narrowed = true
	result.NarrowedOut = len(candidates) - len(kept)
	return result
}

// Dependency manifests drive the deterministic dependency check and are never
// treated as noise, whatever else the built-in rules say. ignore_paths can
// still exclude one — an examples/ app's package.json, say — because that is
// the repo's explicit choice rather than a heuristic.
var manifestNames = map[string]bool{
	"go.mod":           true,
	"package.json":     true,
	"requirements.txt": true,
	"Gemfile":          true,
	"Cargo.toml":       true,
	"pom.xml":          true,
	"build.gradle":     true,
	"composer.json":    true,
	"Pipfile":          true,
	"pyproject.toml":   true,
}

var noiseSegments = []string{"vendor", "node_modules", "dist", "build", "third_party", ".git"}

var noiseFilenames = map[string]bool{
	"package-lock.json": true,
	"pnpm-lock.yaml":    true,
	"go.work.sum":       true,
}

// Note the absence of .txt: requirements.txt is a manifest.
var noiseSuffixes = []string{
	".md", ".rst", ".adoc",
	".svg", ".png", ".jpg", ".jpeg", ".gif", ".ico", ".webp", ".pdf",
	".lock", ".sum", ".min.js", ".map", ".snap",
	".pb.go", "_generated.go", ".generated.go", "_pb2.py",
}

func isNoise(p string) bool {
	if manifestNames[path.Base(p)] {
		return false
	}
	lower := strings.ToLower(p)

	if noiseFilenames[path.Base(lower)] {
		return true
	}
	for _, segment := range noiseSegments {
		if strings.HasPrefix(lower, segment+"/") || strings.Contains(lower, "/"+segment+"/") {
			return true
		}
	}
	for _, suffix := range noiseSuffixes {
		if strings.HasSuffix(lower, suffix) {
			return true
		}
	}
	return false
}

// securitySubstrings mark paths worth keeping when a diff is too large to
// review whole. Matching is generous on purpose: under narrowing a false
// positive costs a few tokens, while a false negative silently hides drift.
var securitySubstrings = []string{
	"auth", "login", "logout", "session", "token", "secret", "password", "passwd",
	"credential", "crypt", "hash", "tls", "ssl", "cert", "jwt", "oauth", "saml",
	"acl", "permission", "privilege", "rbac", "role", "admin", "tenant",
	"handler", "route", "endpoint", "api", "middleware", "server", "client",
	"http", "grpc", "socket", "webhook", "gateway", "proxy", "ingress", "cors",
	"sql", "query", "database", "store", "storage", "repositor", "cache", "migrat",
	"config", "setting", "env", "secret", "deploy", "docker", "terraform",
	"upload", "download", "file", "path", "exec", "command", "shell", "process",
	"serial", "marshal", "parse", "template", "render", "sanitiz", "valid", "escape",
	"user", "account", "profile", "payment", "billing", "order", "invoice",
}

// securityTokens are matched as whole path segments. Short strings like "db"
// would hit half the tree as substrings.
var securityTokens = map[string]bool{"db": true, "id": true, "iam": true, "kms": true}

var configSuffixes = []string{".yml", ".yaml", ".toml", ".ini", ".conf", ".env", ".tf", ".hcl"}

func isSecurityRelevant(p string) bool {
	lower := strings.ToLower(p)

	if manifestNames[path.Base(p)] {
		return true
	}
	for _, suffix := range configSuffixes {
		if strings.HasSuffix(lower, suffix) {
			return true
		}
	}
	for _, keyword := range securitySubstrings {
		if strings.Contains(lower, keyword) {
			return true
		}
	}
	for _, token := range strings.FieldsFunc(lower, func(r rune) bool {
		return r == '/' || r == '.' || r == '_' || r == '-'
	}) {
		if securityTokens[token] {
			return true
		}
	}
	return false
}
