package diff

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGoGenerated(t *testing.T) {
	dir := t.TempDir()
	write := func(rel, contents string) {
		path := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	write("db/queries.go", "// Code generated by sqlc. DO NOT EDIT.\n// versions:\n//   sqlc v1.27.0\n\npackage db\n")
	write("mocks/store.go", "//go:build !prod\n\n/* Licensed under MIT. */\n\n// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n")
	write("auth/session.go", "// Package auth handles sessions.\npackage auth\n")
	// After the package clause the line does not count; go vet agrees.
	write("auth/late.go", "package auth\n\n// Code generated by hand. DO NOT EDIT.\n")
	write("auth/nodot.go", "// Code generated by x. DO NOT EDIT\npackage auth\n")
	// The convention is Go's; a TypeScript file is judged by name alone.
	write("web/client.ts", "// Code generated by openapi. DO NOT EDIT.\nexport {}\n")
	// A licence block longer than the read limit pushes the package clause
	// out of reach, and an unreadable header keeps the file.
	write("big/long.go", "// Code generated by x. DO NOT EDIT.\n/*"+strings.Repeat("x", generatedHeaderBytes)+"*/\npackage big\n")

	root, err := os.OpenRoot(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = root.Close() }()
	generated := GoGenerated(root)

	for path, want := range map[string]bool{
		"db/queries.go":   true,
		"mocks/store.go":  true,
		"auth/session.go": false,
		"auth/late.go":    false,
		"auth/nodot.go":   false,
		"web/client.ts":   false,
		"big/long.go":     false,
		"auth/removed.go": false,
	} {
		if got := generated(path); got != want {
			t.Errorf("generated(%q) = %t, want %t", path, got, want)
		}
	}
}

// A pull request can add a symlink as easily as a file. One pointing out of
// the checkout is refused by the root rather than followed, and a file that
// cannot be read is never called generated.
func TestGoGeneratedRefusesEscapingSymlink(t *testing.T) {
	outside := filepath.Join(t.TempDir(), "outside.go")
	if err := os.WriteFile(outside, []byte("// Code generated by x. DO NOT EDIT.\npackage x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	if err := os.Symlink(outside, filepath.Join(dir, "link.go")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}

	root, err := os.OpenRoot(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = root.Close() }()

	if GoGenerated(root)("link.go") {
		t.Error("a symlink out of the checkout was followed")
	}
}
